name: Deploy Airflow Pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-and-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3 # Ganti sesuai region AWS lo, misal ap-southeast-3 (Jakarta)

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/airflow"
          overwrite: true

      - name: Refresh Airflow Environment in EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/airflow
            chmod -R 755 .
            if [ -d "dags" ]; then
              touch dags/*.py
            fi
            echo "Deploy sukses di folder default Airflow, bray!"