# 2. Kirim file-file dari laptop langsung ke folder default Airflow di EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/airflow" # <--- DIUBAH KE FOLDER DEFAULT
          overwrite: true

      # 3. Eksekusi SSH untuk refresh file di folder default
      - name: Refresh Airflow Environment in EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/airflow # <--- DIUBAH KE FOLDER DEFAULT
            chmod -R 755 .
            if [ -d "dags" ]; then
              touch dags/*.py
            fi
            echo "Deploy sukses di folder default Airflow, bray!"